workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - publish
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_USER/$DOCKER_IMAGE_ECOMMERCE:v1"


create_and_publish_image:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -p $PORT_SERVER $SERVER >> ~/.ssh/known_hosts

  script:
    - echo "Redemarrage des containers ..."
    - ssh $USER@$SERVER "
        cd $REP_ECOMMERCE &&
        docker compose pull &&
        docker compose down &&
        docker compose up -d"
  # when: manual # Ce job doit être déclenché manuellement

